FROM maven:3.9.2-eclipse-temurin-17 AS build
WORKDIR /app
COPY . /app
RUN mvn clean install

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/UzMart-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
