# 1. Build image
FROM maven:3.9.2-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . /app
RUN mvn clean install -DskipTests

# 2. Run image
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/target/UzMart-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
